/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVulnerabilitiesIndexRouteImport } from './routes/_authenticated/vulnerabilities/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedFindingsIndexRouteImport } from './routes/_authenticated/findings/index'
import { Route as AuthenticatedCustomFieldsIndexRouteImport } from './routes/_authenticated/custom-fields/index'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets/index'
import { Route as AuthenticatedVulnerabilitiesIdRouteImport } from './routes/_authenticated/vulnerabilities/$id'
import { Route as AuthenticatedUsersNewRouteImport } from './routes/_authenticated/users/new'
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated/users/$id'
import { Route as AuthenticatedRolesNewRouteImport } from './routes/_authenticated/roles/new'
import { Route as AuthenticatedRolesIdRouteImport } from './routes/_authenticated/roles/$id'
import { Route as AuthenticatedFindingsTriageRouteImport } from './routes/_authenticated/findings/triage'
import { Route as AuthenticatedFindingsNewRouteImport } from './routes/_authenticated/findings/new'
import { Route as AuthenticatedFindingsImportRouteImport } from './routes/_authenticated/findings/import'
import { Route as AuthenticatedFindingsIdRouteImport } from './routes/_authenticated/findings/$id'
import { Route as AuthenticatedCustomFieldsNewRouteImport } from './routes/_authenticated/custom-fields/new'
import { Route as AuthenticatedCustomFieldsIdRouteImport } from './routes/_authenticated/custom-fields/$id'
import { Route as AuthenticatedAssetsIdRouteImport } from './routes/_authenticated/assets/$id'
import { Route as AuthenticatedUsersIdEditRouteImport } from './routes/_authenticated/users/$id.edit'
import { Route as AuthenticatedRolesIdEditRouteImport } from './routes/_authenticated/roles/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVulnerabilitiesIndexRoute =
  AuthenticatedVulnerabilitiesIndexRouteImport.update({
    id: '/vulnerabilities/',
    path: '/vulnerabilities/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFindingsIndexRoute =
  AuthenticatedFindingsIndexRouteImport.update({
    id: '/findings/',
    path: '/findings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomFieldsIndexRoute =
  AuthenticatedCustomFieldsIndexRouteImport.update({
    id: '/custom-fields/',
    path: '/custom-fields/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVulnerabilitiesIdRoute =
  AuthenticatedVulnerabilitiesIdRouteImport.update({
    id: '/vulnerabilities/$id',
    path: '/vulnerabilities/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesNewRoute = AuthenticatedRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesIdRoute = AuthenticatedRolesIdRouteImport.update({
  id: '/roles/$id',
  path: '/roles/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFindingsTriageRoute =
  AuthenticatedFindingsTriageRouteImport.update({
    id: '/findings/triage',
    path: '/findings/triage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFindingsNewRoute =
  AuthenticatedFindingsNewRouteImport.update({
    id: '/findings/new',
    path: '/findings/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFindingsImportRoute =
  AuthenticatedFindingsImportRouteImport.update({
    id: '/findings/import',
    path: '/findings/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFindingsIdRoute = AuthenticatedFindingsIdRouteImport.update({
  id: '/findings/$id',
  path: '/findings/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomFieldsNewRoute =
  AuthenticatedCustomFieldsNewRouteImport.update({
    id: '/custom-fields/new',
    path: '/custom-fields/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomFieldsIdRoute =
  AuthenticatedCustomFieldsIdRouteImport.update({
    id: '/custom-fields/$id',
    path: '/custom-fields/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsIdRoute = AuthenticatedAssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIdEditRoute =
  AuthenticatedUsersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedUsersIdRoute,
  } as any)
const AuthenticatedRolesIdEditRoute =
  AuthenticatedRolesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedRolesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/custom-fields/$id': typeof AuthenticatedCustomFieldsIdRoute
  '/custom-fields/new': typeof AuthenticatedCustomFieldsNewRoute
  '/findings/$id': typeof AuthenticatedFindingsIdRoute
  '/findings/import': typeof AuthenticatedFindingsImportRoute
  '/findings/new': typeof AuthenticatedFindingsNewRoute
  '/findings/triage': typeof AuthenticatedFindingsTriageRoute
  '/roles/$id': typeof AuthenticatedRolesIdRouteWithChildren
  '/roles/new': typeof AuthenticatedRolesNewRoute
  '/users/$id': typeof AuthenticatedUsersIdRouteWithChildren
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/vulnerabilities/$id': typeof AuthenticatedVulnerabilitiesIdRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/custom-fields/': typeof AuthenticatedCustomFieldsIndexRoute
  '/findings/': typeof AuthenticatedFindingsIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/vulnerabilities/': typeof AuthenticatedVulnerabilitiesIndexRoute
  '/roles/$id/edit': typeof AuthenticatedRolesIdEditRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/custom-fields/$id': typeof AuthenticatedCustomFieldsIdRoute
  '/custom-fields/new': typeof AuthenticatedCustomFieldsNewRoute
  '/findings/$id': typeof AuthenticatedFindingsIdRoute
  '/findings/import': typeof AuthenticatedFindingsImportRoute
  '/findings/new': typeof AuthenticatedFindingsNewRoute
  '/findings/triage': typeof AuthenticatedFindingsTriageRoute
  '/roles/$id': typeof AuthenticatedRolesIdRouteWithChildren
  '/roles/new': typeof AuthenticatedRolesNewRoute
  '/users/$id': typeof AuthenticatedUsersIdRouteWithChildren
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/vulnerabilities/$id': typeof AuthenticatedVulnerabilitiesIdRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/custom-fields': typeof AuthenticatedCustomFieldsIndexRoute
  '/findings': typeof AuthenticatedFindingsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vulnerabilities': typeof AuthenticatedVulnerabilitiesIndexRoute
  '/roles/$id/edit': typeof AuthenticatedRolesIdEditRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/_authenticated/custom-fields/$id': typeof AuthenticatedCustomFieldsIdRoute
  '/_authenticated/custom-fields/new': typeof AuthenticatedCustomFieldsNewRoute
  '/_authenticated/findings/$id': typeof AuthenticatedFindingsIdRoute
  '/_authenticated/findings/import': typeof AuthenticatedFindingsImportRoute
  '/_authenticated/findings/new': typeof AuthenticatedFindingsNewRoute
  '/_authenticated/findings/triage': typeof AuthenticatedFindingsTriageRoute
  '/_authenticated/roles/$id': typeof AuthenticatedRolesIdRouteWithChildren
  '/_authenticated/roles/new': typeof AuthenticatedRolesNewRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRouteWithChildren
  '/_authenticated/users/new': typeof AuthenticatedUsersNewRoute
  '/_authenticated/vulnerabilities/$id': typeof AuthenticatedVulnerabilitiesIdRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/custom-fields/': typeof AuthenticatedCustomFieldsIndexRoute
  '/_authenticated/findings/': typeof AuthenticatedFindingsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/vulnerabilities/': typeof AuthenticatedVulnerabilitiesIndexRoute
  '/_authenticated/roles/$id/edit': typeof AuthenticatedRolesIdEditRoute
  '/_authenticated/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/assets/$id'
    | '/custom-fields/$id'
    | '/custom-fields/new'
    | '/findings/$id'
    | '/findings/import'
    | '/findings/new'
    | '/findings/triage'
    | '/roles/$id'
    | '/roles/new'
    | '/users/$id'
    | '/users/new'
    | '/vulnerabilities/$id'
    | '/assets/'
    | '/custom-fields/'
    | '/findings/'
    | '/roles/'
    | '/users/'
    | '/vulnerabilities/'
    | '/roles/$id/edit'
    | '/users/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/assets/$id'
    | '/custom-fields/$id'
    | '/custom-fields/new'
    | '/findings/$id'
    | '/findings/import'
    | '/findings/new'
    | '/findings/triage'
    | '/roles/$id'
    | '/roles/new'
    | '/users/$id'
    | '/users/new'
    | '/vulnerabilities/$id'
    | '/assets'
    | '/custom-fields'
    | '/findings'
    | '/roles'
    | '/users'
    | '/vulnerabilities'
    | '/roles/$id/edit'
    | '/users/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/assets/$id'
    | '/_authenticated/custom-fields/$id'
    | '/_authenticated/custom-fields/new'
    | '/_authenticated/findings/$id'
    | '/_authenticated/findings/import'
    | '/_authenticated/findings/new'
    | '/_authenticated/findings/triage'
    | '/_authenticated/roles/$id'
    | '/_authenticated/roles/new'
    | '/_authenticated/users/$id'
    | '/_authenticated/users/new'
    | '/_authenticated/vulnerabilities/$id'
    | '/_authenticated/assets/'
    | '/_authenticated/custom-fields/'
    | '/_authenticated/findings/'
    | '/_authenticated/roles/'
    | '/_authenticated/users/'
    | '/_authenticated/vulnerabilities/'
    | '/_authenticated/roles/$id/edit'
    | '/_authenticated/users/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vulnerabilities/': {
      id: '/_authenticated/vulnerabilities/'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities/'
      preLoaderRoute: typeof AuthenticatedVulnerabilitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/findings/': {
      id: '/_authenticated/findings/'
      path: '/findings'
      fullPath: '/findings/'
      preLoaderRoute: typeof AuthenticatedFindingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/custom-fields/': {
      id: '/_authenticated/custom-fields/'
      path: '/custom-fields'
      fullPath: '/custom-fields/'
      preLoaderRoute: typeof AuthenticatedCustomFieldsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vulnerabilities/$id': {
      id: '/_authenticated/vulnerabilities/$id'
      path: '/vulnerabilities/$id'
      fullPath: '/vulnerabilities/$id'
      preLoaderRoute: typeof AuthenticatedVulnerabilitiesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/new': {
      id: '/_authenticated/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/new': {
      id: '/_authenticated/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof AuthenticatedRolesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/$id': {
      id: '/_authenticated/roles/$id'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof AuthenticatedRolesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/findings/triage': {
      id: '/_authenticated/findings/triage'
      path: '/findings/triage'
      fullPath: '/findings/triage'
      preLoaderRoute: typeof AuthenticatedFindingsTriageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/findings/new': {
      id: '/_authenticated/findings/new'
      path: '/findings/new'
      fullPath: '/findings/new'
      preLoaderRoute: typeof AuthenticatedFindingsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/findings/import': {
      id: '/_authenticated/findings/import'
      path: '/findings/import'
      fullPath: '/findings/import'
      preLoaderRoute: typeof AuthenticatedFindingsImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/findings/$id': {
      id: '/_authenticated/findings/$id'
      path: '/findings/$id'
      fullPath: '/findings/$id'
      preLoaderRoute: typeof AuthenticatedFindingsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/custom-fields/new': {
      id: '/_authenticated/custom-fields/new'
      path: '/custom-fields/new'
      fullPath: '/custom-fields/new'
      preLoaderRoute: typeof AuthenticatedCustomFieldsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/custom-fields/$id': {
      id: '/_authenticated/custom-fields/$id'
      path: '/custom-fields/$id'
      fullPath: '/custom-fields/$id'
      preLoaderRoute: typeof AuthenticatedCustomFieldsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/$id': {
      id: '/_authenticated/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$id/edit': {
      id: '/_authenticated/users/$id/edit'
      path: '/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof AuthenticatedUsersIdEditRouteImport
      parentRoute: typeof AuthenticatedUsersIdRoute
    }
    '/_authenticated/roles/$id/edit': {
      id: '/_authenticated/roles/$id/edit'
      path: '/edit'
      fullPath: '/roles/$id/edit'
      preLoaderRoute: typeof AuthenticatedRolesIdEditRouteImport
      parentRoute: typeof AuthenticatedRolesIdRoute
    }
  }
}

interface AuthenticatedRolesIdRouteChildren {
  AuthenticatedRolesIdEditRoute: typeof AuthenticatedRolesIdEditRoute
}

const AuthenticatedRolesIdRouteChildren: AuthenticatedRolesIdRouteChildren = {
  AuthenticatedRolesIdEditRoute: AuthenticatedRolesIdEditRoute,
}

const AuthenticatedRolesIdRouteWithChildren =
  AuthenticatedRolesIdRoute._addFileChildren(AuthenticatedRolesIdRouteChildren)

interface AuthenticatedUsersIdRouteChildren {
  AuthenticatedUsersIdEditRoute: typeof AuthenticatedUsersIdEditRoute
}

const AuthenticatedUsersIdRouteChildren: AuthenticatedUsersIdRouteChildren = {
  AuthenticatedUsersIdEditRoute: AuthenticatedUsersIdEditRoute,
}

const AuthenticatedUsersIdRouteWithChildren =
  AuthenticatedUsersIdRoute._addFileChildren(AuthenticatedUsersIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAssetsIdRoute: typeof AuthenticatedAssetsIdRoute
  AuthenticatedCustomFieldsIdRoute: typeof AuthenticatedCustomFieldsIdRoute
  AuthenticatedCustomFieldsNewRoute: typeof AuthenticatedCustomFieldsNewRoute
  AuthenticatedFindingsIdRoute: typeof AuthenticatedFindingsIdRoute
  AuthenticatedFindingsImportRoute: typeof AuthenticatedFindingsImportRoute
  AuthenticatedFindingsNewRoute: typeof AuthenticatedFindingsNewRoute
  AuthenticatedFindingsTriageRoute: typeof AuthenticatedFindingsTriageRoute
  AuthenticatedRolesIdRoute: typeof AuthenticatedRolesIdRouteWithChildren
  AuthenticatedRolesNewRoute: typeof AuthenticatedRolesNewRoute
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRouteWithChildren
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute
  AuthenticatedVulnerabilitiesIdRoute: typeof AuthenticatedVulnerabilitiesIdRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedCustomFieldsIndexRoute: typeof AuthenticatedCustomFieldsIndexRoute
  AuthenticatedFindingsIndexRoute: typeof AuthenticatedFindingsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVulnerabilitiesIndexRoute: typeof AuthenticatedVulnerabilitiesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAssetsIdRoute: AuthenticatedAssetsIdRoute,
  AuthenticatedCustomFieldsIdRoute: AuthenticatedCustomFieldsIdRoute,
  AuthenticatedCustomFieldsNewRoute: AuthenticatedCustomFieldsNewRoute,
  AuthenticatedFindingsIdRoute: AuthenticatedFindingsIdRoute,
  AuthenticatedFindingsImportRoute: AuthenticatedFindingsImportRoute,
  AuthenticatedFindingsNewRoute: AuthenticatedFindingsNewRoute,
  AuthenticatedFindingsTriageRoute: AuthenticatedFindingsTriageRoute,
  AuthenticatedRolesIdRoute: AuthenticatedRolesIdRouteWithChildren,
  AuthenticatedRolesNewRoute: AuthenticatedRolesNewRoute,
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRouteWithChildren,
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedVulnerabilitiesIdRoute: AuthenticatedVulnerabilitiesIdRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedCustomFieldsIndexRoute: AuthenticatedCustomFieldsIndexRoute,
  AuthenticatedFindingsIndexRoute: AuthenticatedFindingsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVulnerabilitiesIndexRoute:
    AuthenticatedVulnerabilitiesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
