export { createAssets } from "./assets.js";
export type {
  AddAssetIdentifierCommand,
  AssetCreatedOutcome,
  AssetCustomFieldAssignmentsReplacedOutcome,
  AssetCustomFieldDefinitionCreatedOutcome,
  AssetCustomFieldDefinitionDeletedOutcome,
  AssetCustomFieldDefinitionUpdatedOutcome,
  AssetCustomFields,
  AssetCustomFieldValuesReplacedOutcome,
  AssetDeletedOutcome,
  AssetIdentifierAddedOutcome,
  AssetIdentifierDeletedOutcome,
  AssetIdentifierUpdatedOutcome,
  AssetInventory,
  AssetListOptions,
  Assets,
  AssetUpdatedOutcome,
  CreateAssetCommand,
  CreateAssetCustomFieldDefinitionCommand,
  DeleteAssetByIDCommand,
  DeleteAssetCustomFieldDefinitionByIDCommand,
  DeleteAssetIdentifierByIDCommand,
  ReplaceAssetCustomFieldAssignmentsCommand,
  ReplaceAssetCustomFieldValuesCommand,
  UpdateAssetByIDCommand,
  UpdateAssetCustomFieldDefinitionByIDCommand,
  UpdateAssetIdentifierByIDCommand,
} from "./assets.js";
